export CGO_ENABLED := 0
export GOEXPERIMENT := jsonv2

# renovate: datasource=github-releases depName=golangci/golangci-lint
GOLANGCI_LINT_VERSION := v2.12.2

# Hugo is a tool dependency (see the tool directive in go.mod), so the version the site is built
# with is pinned there and needs nothing installed. HUGO overrides it with another binary.
HUGO ?= go tool hugo

# Port for site-serve.
SITE_PORT ?= 1313

VERSION := $(shell git describe --tags --always --dirty 2>/dev/null || echo dev)
REVISION := $(shell git rev-parse --short HEAD 2>/dev/null || echo unknown)
GOBUILDFLAGS := -trimpath -ldflags="-s -w -X main.version=$(VERSION) -X main.revision=$(REVISION)"

.DEFAULT_GOAL := help

.PHONY: help
help: ## Show this help message
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-15s\033[0m %s\n", $$1, $$2}'

.PHONY: build
build: OUTPUT ?= bin/decolint
build: ## Build the decolint binary
	go build $(GOBUILDFLAGS) -o $(OUTPUT) ./cmd/decolint

.PHONY: run
run: build ## Build and run the decolint binary
	./bin/decolint $(ARGS)

.PHONY: test
test: ## Run all tests
	go test ./...

.PHONY: coverage
coverage: ## Run tests and open an HTML coverage report
	go test -coverprofile=coverage.out ./...
	go tool cover -func=coverage.out
	go tool cover -html=coverage.out -o coverage.html

.PHONY: lint
lint: ## Run all lint rules
	go run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@$(GOLANGCI_LINT_VERSION) run

.PHONY: site
site: site-content ## Build the documentation site into docs/public
	$(HUGO) --source docs --minify

.PHONY: site-serve
site-serve: site-content ## Serve the documentation site with live reload
	# hugo server keeps the path of the configured baseURL, which would serve the site under
	# /decolint/ and leave http://localhost:$(SITE_PORT)/ a 404. Override it for local preview.
	$(HUGO) server --source docs --port $(SITE_PORT) --baseURL http://localhost:$(SITE_PORT)/

.PHONY: site-content
site-content: ## Regenerate the rule pages, README-derived pages, and README rules table
	go run ./cmd/docgen

.PHONY: site-syntax
site-syntax: ## Regenerate the syntax highlighting stylesheet
	@{ \
		echo '/* Chroma syntax highlighting token colors.'; \
		echo '   Generated by `make site-syntax`; edit that target rather than this file. */'; \
		echo; \
		$(HUGO) gen chromastyles --style=github | tail -n +2; \
		echo '@media (prefers-color-scheme: dark) {'; \
		$(HUGO) gen chromastyles --style=github-dark | tail -n +2 | sed 's/^./  &/'; \
		echo '}'; \
	} > docs/assets/css/syntax.css

.PHONY: clean
clean: ## Remove build artifacts
	rm -rf bin coverage.out coverage.html docs/public docs/resources docs/.generated docs/.hugo_build.lock .hugo_build.lock

.PHONY: install
install: ## Install the decolint binary to GOPATH/bin
	go install $(GOBUILDFLAGS) ./cmd/decolint
