export CGO_ENABLED := 0
export GOEXPERIMENT := jsonv2

# renovate: datasource=github-releases depName=golangci/golangci-lint
GOLANGCI_LINT_VERSION := v2.12.2

# renovate: datasource=github-releases depName=gohugoio/hugo
HUGO_VERSION := v0.164.0

# The site is built with whichever hugo is on PATH; HUGO overrides it, e.g. to a downloaded
# release. Its version is pinned in the Pages workflow, which is what publishes the site.
HUGO ?= hugo

# Port for site-serve.
SITE_PORT ?= 1313

VERSION := $(shell git describe --tags --always --dirty 2>/dev/null || echo dev)
REVISION := $(shell git rev-parse --short HEAD 2>/dev/null || echo unknown)
GOBUILDFLAGS := -trimpath -ldflags="-s -w -X main.version=$(VERSION) -X main.revision=$(REVISION)"

.DEFAULT_GOAL := help

.PHONY: help
help: ## Show this help message
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-15s\033[0m %s\n", $$1, $$2}'

.PHONY: build
build: OUTPUT ?= bin/decolint
build: ## Build the decolint binary
	go build $(GOBUILDFLAGS) -o $(OUTPUT) ./cmd/decolint

.PHONY: run
run: build ## Build and run the decolint binary
	./bin/decolint $(ARGS)

.PHONY: test
test: ## Run all tests
	go test ./...

.PHONY: coverage
coverage: ## Run tests and open an HTML coverage report
	go test -coverprofile=coverage.out ./...
	go tool cover -func=coverage.out
	go tool cover -html=coverage.out -o coverage.html

.PHONY: lint
lint: ## Run all lint rules
	go run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@$(GOLANGCI_LINT_VERSION) run

.PHONY: site
site: check-hugo ## Build the documentation site into docs/public
	$(HUGO) --source docs --minify

.PHONY: site-serve
site-serve: check-hugo ## Serve the documentation site with live reload
	# hugo server keeps the path of the configured baseURL, which would serve the site under
	# /decolint/ and leave http://localhost:$(SITE_PORT)/ a 404. Override it for local preview.
	$(HUGO) server --source docs --port $(SITE_PORT) --baseURL http://localhost:$(SITE_PORT)/

.PHONY: site-syntax
site-syntax: check-hugo ## Regenerate the syntax highlighting stylesheet
	@{ \
		echo '/* Chroma syntax highlighting token colours.'; \
		echo '   Generated by `make site-syntax`; edit that target rather than this file. */'; \
		echo; \
		$(HUGO) gen chromastyles --style=github | tail -n +2; \
		echo '@media (prefers-color-scheme: dark) {'; \
		$(HUGO) gen chromastyles --style=github-dark | tail -n +2 | sed 's/^./  &/'; \
		echo '}'; \
	} > docs/assets/css/syntax.css

# The site's templates use the flat layouts/ lookup Hugo introduced in 0.146. An older hugo does
# not fail on them: it renders the pages it cannot find a layout for as empty ones, so check the
# version rather than let that reach the browser.
.PHONY: check-hugo
check-hugo:
	@have=$$($(HUGO) version 2>/dev/null | sed -n 's/^hugo v\([0-9][0-9.]*\).*/\1/p'); \
	want=$(HUGO_VERSION:v%=%); \
	if [ -z "$$have" ]; then \
		echo "$(HUGO): not found; install Hugo $$want or newer, or set HUGO=/path/to/hugo" >&2; \
		exit 1; \
	fi; \
	if [ "$$(printf '%s\n%s\n' "$$want" "$$have" | sort -V | head -n 1)" != "$$want" ]; then \
		echo "hugo $$have is older than $$want, which the site's layouts need" >&2; \
		exit 1; \
	fi

.PHONY: clean
clean: ## Remove build artifacts
	rm -rf bin coverage.out coverage.html docs/public docs/resources docs/.hugo_build.lock .hugo_build.lock

.PHONY: install
install: ## Install the decolint binary to GOPATH/bin
	go install $(GOBUILDFLAGS) ./cmd/decolint
