// Command dockerflagsgen writes the table of "docker run" flags that package dockerargs parses
// with, by building the command docker/cli builds and reading back the flags it registered. A table
// written by hand goes stale the moment Docker adds a flag, and it goes stale silently: decolint
// keeps parsing, just no longer the way Docker does.
//
// It is a module of its own so that decolint neither imports nor vendors docker/cli, and so that
// "go build", "go test" and the linter, which all work on the module rooted at the repository root,
// never reach it. Run it with "make dockerflags".
package main

import (
	"flag"
	"fmt"
	"go/format"
	"os"
	"runtime/debug"
	"sort"
	"strings"

	"github.com/docker/cli/cli/command"
	"github.com/docker/cli/cli/command/commands"
	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

const dockerCLIModule = "github.com/docker/cli"

func main() {
	out := flag.String("o", "", "write the table to this file instead of standard output")
	flag.Parse()

	src, err := generate()
	if err != nil {
		fmt.Fprintln(os.Stderr, "dockerflagsgen:", err)
		os.Exit(1)
	}
	if *out == "" {
		if _, err := os.Stdout.Write(src); err != nil {
			fmt.Fprintln(os.Stderr, "dockerflagsgen:", err)
			os.Exit(1)
		}
		return
	}
	if err := os.WriteFile(*out, src, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "dockerflagsgen:", err)
		os.Exit(1)
	}
}

func generate() ([]byte, error) {
	flags, err := RunFlagSet()
	if err != nil {
		return nil, err
	}
	src, err := format.Source([]byte(render(flags, dockerCLIVersion())))
	if err != nil {
		return nil, fmt.Errorf("formatting the generated table: %w", err)
	}
	return src, nil
}

// RunFlagSet returns the flags "docker run" registers, as docker/cli registers them: on the command
// its own command tree hands to cobra, rather than on a set assembled here that could drift from it.
func RunFlagSet() (*pflag.FlagSet, error) {
	dockerCLI, err := command.NewDockerCli()
	if err != nil {
		return nil, fmt.Errorf("creating a docker CLI: %w", err)
	}
	root := &cobra.Command{Use: "docker"}
	commands.AddCommands(root, dockerCLI)
	for _, cmd := range root.Commands() {
		if cmd.Name() == "run" {
			return cmd.Flags(), nil
		}
	}
	return nil, fmt.Errorf("docker/cli registered no %q command", "run")
}

// dockerCLIVersion returns the version of docker/cli this binary was built against, or "" if the
// build carries no information about it.
func dockerCLIVersion() string {
	info, ok := debug.ReadBuildInfo()
	if !ok {
		return ""
	}
	for _, dep := range info.Deps {
		if dep.Path == dockerCLIModule {
			return dep.Version
		}
	}
	return ""
}

func render(flags *pflag.FlagSet, version string) string {
	var names []string
	byName := map[string]*pflag.Flag{}
	flags.VisitAll(func(f *pflag.Flag) {
		names = append(names, f.Name)
		byName[f.Name] = f
	})
	sort.Strings(names)

	var b strings.Builder
	b.WriteString("// Code generated by cmd/dockerflagsgen; DO NOT EDIT.\n\n")
	b.WriteString("package dockerargs\n\n")
	b.WriteString("// RunFlags is every flag \"docker run\" registers")
	if version != "" {
		fmt.Fprintf(&b, ", as of %s %s", dockerCLIModule, version)
	}
	b.WriteString(".\n")
	b.WriteString("// It includes the hidden and deprecated ones, which Docker still parses.\n")
	b.WriteString("//\n")
	b.WriteString("// A flag is identified by its name, never by the spelling an argv uses: \"--net\" is not the\n")
	b.WriteString("// short form of \"--network\" but a flag docker/cli registers separately, while \"-v\" is the\n")
	b.WriteString("// shorthand of \"--volume\" and reaches the same entry here.\n")
	b.WriteString("var RunFlags = []Flag{\n")
	for _, name := range names {
		f := byName[name]
		fmt.Fprintf(&b, "\t{Name: %q", f.Name)
		if f.Shorthand != "" {
			fmt.Fprintf(&b, ", Shorthand: %q", f.Shorthand)
		}
		fmt.Fprintf(&b, ", Type: %q", f.Value.Type())
		if f.NoOptDefVal != "" {
			fmt.Fprintf(&b, ", NoOptDefVal: %q", f.NoOptDefVal)
		}
		b.WriteString("},\n")
	}
	b.WriteString("}\n")
	return b.String()
}
